image:
  name: pagespeed_exporter
  repository: foomo/pagespeed_exporter
  pullPolicy: Always
  tag: ""

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80
  annotations:
    prometheus.io/scrape: "true"

targetPort: 9271

resources: {}

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}

exporter:
  googleapikey: ""
  pushGatewayUrl: ""
  targets: []

cronjob:
  enabled: false
  image:
    name: curl
    repository: curlimages/curl
    pullPolicy: Always
    tag: 7.73.0
  # Executes every 10 minutes
  schedule: "*/10 * * * *"
  scrapeTimeoutSeconds: 120
