name: pagespeed-exporter

service:
  type: ClusterIP
  port: 9271
  annotations:
    prometheus.io/scrape: "true"

replicas: 1

image:
  name: pagespeed_exporter
  repository: foomo/pagespeed_exporter
  tag: latest
  pullPolicy: IfNotPresent

exporter:
  googleapikey: ""
  targets:
    - https://www.google.com
    - https://www.google.com/webhp
