version: "3.7"

services:
  pagespeed_exporter:
    image: foomo/pagespeed_exporter:latest
    restart: unless-stopped
    command:
    - "-targets=https://www.google.com"
    # - "-api-key=${MY_API_KEY}"

  prometheus:
    restart: unless-stopped
    image: prom/prometheus:latest
    command:
    - "--config.file=/etc/prometheus/prometheus.yml"
    ports:
    - "9090:9090"
    volumes:
    - "./prometheus/config.yml:/etc/prometheus/prometheus.yml:ro"

  grafana:
    restart: unless-stopped
    image: grafana/grafana:latest
    ports:
    - "3000:3000"
    environment:
    - GF_SECURITY_ADMIN_PASSWORD=s3cr3t
