language: go
go:
  - 1.12.5
  - latest

env:
  - GO111MODULE=on

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

services:
  - docker

script:
  - make
  - if [[ -n "${TRAVIS_TAG}" ]]; then
    make release;
    fi