language: go
go:
  - 1.11.2

services:
  - docker

cache:
  directories:
    - ./vendor

script:
  - make
  - if [[ -n "${TRAVIS_TAG}" ]]; then
      DOCKER_IMAGE_TAG=${TRAVIS_TAG} make docker-build;
      DOCKER_IMAGE_TAG=${TRAVIS_TAG} make docker-push;
    fi
