language: go
go:
  - 1.11

sudo: required

services:
  - docker

script:
  - make

after_success:
  - if [[ -n "${TRAVIS_TAG}" ]]; then
    DOCKER_IMAGE_TAG=${TRAVIS_TAG} make docker-build;
    DOCKER_IMAGE_TAG=${TRAVIS_TAG} make docker-push;
  fi