apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  annotations:
  {{- with .Values.service.annotations }}
  {{ toYaml . | indent 4 }}
  {{- end }}
  labels:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    {{- with .Values.service.labels }}
    {{ toYaml . | indent 4 }}
    {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app.kubernetes.io/name: {{ .Values.name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  ports:
    - port: {{ .Values.service.port}}
      name: http
      targetPort: http
