global:
  scrape_interval: 15s # By default, scrape targets every 15 seconds.
  scrape_timeout: 15s

scrape_configs:
- job_name: pagespeed_exporter
  scrape_interval: 60s
  scrape_timeout: 60s
  static_configs:
  - targets: ['pagespeed_exporter:9271']
    labels:
      instance: local