global:
  scrape_interval: 1h # By default, scrape targets every 15 seconds.
  scrape_timeout: 30s

scrape_configs:
  - job_name: pagespeed_exporter
    metrics_path: /probe
    # Re-Label configurations so that we can use them
    # to configure the pagespeed exporter
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: "pagespeed_exporter:9271"
    static_configs:
      - targets:
          - "https://example.com/"
