name: pagespeed-exporter
replicas: 1

service:
  type: ClusterIP
  port: 9271
  annotations:
    prometheus.io/scrape: "true"

image:
  name: pagespeed_exporter
  repository: foomo/pagespeed_exporter
  tag: latest

exporter:
  googleapikey: ""
  targets:
  - https://www.google.com
  - https://www.google.com/webhp
