apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "fullname" . }}
  labels:
    app.kubernetes.io/name: {{ template "name" . }}
    app.kubernetes.io/instance: {{ $.Release.Name | quote }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ template "name" . }}
      app.kubernetes.io/instance: {{ $.Release.Name | quote }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ template "name" . }}
        app.kubernetes.io/instance: {{ $.Release.Name }}
    spec:
      containers:
      - name: {{ template "name" . }}
        {{- with .Values.image }}
        image: {{ .repository }}:{{ .tag }}
        imagePullPolicy: {{ .pullPolicy }}
        {{- end }}
        args:
        - "-api-key={{ .Values.exporter.googleapikey }}"
        {{- range $_, $target := .Values.exporter.targets }}
        - "-t={{ $target }}"
        {{- end }}
        ports:
          - containerPort: {{ .Values.service.port }}
            protocol: TCP
