apiVersion: v1
kind: Service
apiVersion: v1
kind: Service
metadata:
  name: {{ include "pagespeed-exporter.fullname" . }}
  labels:
    {{- include "pagespeed-exporter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.targetPort }}
      protocol: TCP
      name: http
  selector:
    {{- include "pagespeed-exporter.selectorLabels" . | nindent 4 }}
